config/routes.rb
Rails.application.routes.draw do
  resources :types do
    resources :species
  end

  resources :species do
    resources :sightings
  end
end

app/models/sighting.rb
class Sighting < ActiveRecord::Base
    belongs_to :species
end

app/models/species.rb
class Species < ActiveRecord::Base
  has_many :sightings
  belongs_to :type
  validates :name, :presence => true
  validates :description, :presence => true
end

app/models/type.rb
class Type < ActiveRecord::Base
  has_many :species
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  def new
    @species = Species.find(params[:species_id])
    @sighting = @species.sightings.new
  end

  def create
    @species = Species.find(params[:species_id])
    @sighting = @species.sightings.new(sighting_params)
    if @sighting.save
      flash[:notice] = "Sighting Added"
      redirect_to species_path(@sighting.species)
    else
      render :new
    end
  end

  private
  def sighting_params
    params.require(:sighting).permit(:latitude, :longtitude)
  end


end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  def show
    @species = Species.find(params[:id])
    render :show
  end

  def new
    @type = Type.find(params[:type_id])
    @species = @type.species.new
    render :new
  end

  def create
    @type = Type.find(params[:type_id])
    @species = @type.species.new(species_params)
    if @species.save
      redirect_to type_path(@species.type)
    else
      render :new
    end
  end

  private

  def species_params
    params.require(:species).permit(:name, :description)
  end


end

app/controllers/types_controller.rb
class TypesController < ApplicationController

  def index
    @types = Type.all
    render :index
  end

  def show
    @type = Type.find(params[:id])
    render :show
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WildlifeTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sightings/new.html.erb
<% content_for(:title, "New Sighting") %>

<%= form_for [@species, @sighting ] do |f| %>
  <%= f.label :latitude %>
  <%= f.number_field :latitude %>
  <%= f.label :longitude %>
  <%= f.number_field :longtitude %>
  <%= f.submit %>
<% end %>

app/views/species/new.html.erb
<% content_for(:title, "New Species") %>

<h1>New species for <%= @type.name %></h1>

<%= form_for [@type, @species] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/species/show.html.erb
<h1><%= @species.name %></h1>

<% if @species.sightings.any? %>
  <h4>Current <%= @species.name %> sightings:</h4>
  <ul>
    <% @species.sightings.each do |sighting| %>
      <li><%= sighting.latitude %> - <%= sighting.longtitude %></li>
    <% end %>
  </ul>
  <% else %>
    <p>Add a Sighting</p>
<% end %>

<%= link_to "Add a Sighting", new_species_sighting_path(@species) %>

app/views/types/index.html.erb
<h1>All Types</h1>

<ul>
  <% @types.each do |type| %>
    <li><%=link_to type.name, type_path(type) %></li>
  <% end %>
</ul>

<link-to 

app/views/types/show.html.erb
<h1><%= @type.name %></h1>
<ul>
  <% @type.species.each do |species| %>
    <li>
      <%=link_to species.name, type_species_path(@type, species) %>
    </li>
  <% end %>
</ul>

<%= link_to "Add a New Species", new_type_species_path(@type) %>